### ISSUE TITLE
abbreviated meeting 4/23 same time

### ISSUE THREAD

**Issue by AndrewAnnex** [USGS-Astrogeology/TSC#41]
see #40, I can be available at the regular time of the meeting and will set many reminders if this is confirmed, if not I will wait until next scheduled meeting. I don't know the procedure for calling for a meeting so if someone else can help me with that, thanks!

**Comment by rbeyer** [comment]
It is as simple as putting in a PR for a meeting over in TSC/meetings/ with the agenda. If you don't have the capacity to host a telecon or a Zoom meeting or a WebEx yourself, ask if the USGS folks can host it.  It is a bit of a short fuse for a next Tuesday meeting, but since you're just folks to get on the line and talk, nobody has to prepare anything, so that is probably easy.
